CREATE TABLE SHOHIN (
 SHOHIN_CODE VARCHAR(7) PRIMARY KEY,
 SHOHIN_NAME VARCHAR(80) NOT NULL,
 SHOHIN_VOL VARCHAR(20),
 SHOHIN_PRICE INT,
 SHOHIN_AREA VARCHAR(30),
 SHOHIN_COMMENT VARCHAR(110),
 SHOHIN_IMAGE VARCHAR(20)
);
